from dotenv import load_dotenv
import os

load_dotenv()

DB_APIKEY = os.getenv("FIREBASE_APIKEY")
DB_AUTHDOMAIN = os.getenv("FIREBASE_AUTHDOMAIN")
DB_PROJECTID = os.getenv("FIREBASE_PROJECTID")
DB_STORAGEBUKET = os.getenv("FIREBASE_STORAGEBUKET")
DB_MESSAGINGSENDERID = os.getenv("FIREBASE_MESSAGINGSENDERID")
DB_APPID = os.getenv("FIREBASE_APPID")
DB_MEASUREMENTID = os.getenv("FIREBASE_MEASUREMENTID")
CLIENT_URL = os.getenv("CLIENT_URL") 